fos_user:
    db_driver: orm
    firewall_name: main
    user_class: AppBundle\Entity\User
    from_email:
        address: "%mailer_user_address%"
        sender_name: "%mailer_user_name%"
    service:
        mailer: fos_user.mailer.noop
