security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    role_hierarchy:
        ROLE_SUPER_ADMIN:
            - ROLE_ADMIN

        ROLE_ADMIN:
            - ROLE_ADMIN_USER_LIST
            - ROLE_ADMIN_USER_VIEW
            - ROLE_ADMIN_USER_CREATE
            - ROLE_ADMIN_USER_EDIT
            - ROLE_ADMIN_USER_DELETE
            -
            - ROLE_ADMIN_NODE_POST_LIST
            - ROLE_ADMIN_NODE_POST_VIEW
            - ROLE_ADMIN_NODE_POST_CREATE
            - ROLE_ADMIN_NODE_POST_EDIT
            - ROLE_ADMIN_NODE_POST_DELETE

            - ROLE_ADMIN_PARAMETER_LIST

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            user_checker: fos_user.user_checker
            logout:
                path: fos_user_security_logout
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                provider: fos_userbundle
                enable_csrf: true

    access_control:
         - { path: ^/admin, roles: ROLE_ADMIN }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
