sonata_admin:
    title: 'LMJ'
    search: false

    options:
        html5_validate: false

    global_search:
        empty_boxes: hide

    dashboard:
        blocks:
            - { type: admin.block.statistique, position: top, class: col-xs-12 }
            - { type: admin.block.server-statistique, position: right }
            - { type: admin.block.app, position: right }

        groups:
            homepage:
                label: Home
                on_top: true
                icon: '<i class="fa fa-dashboard"></i>'
                items:
                    - { label: Dashboard, route: sonata_admin_dashboard }
            app.admin.group.user:
                label: User List
                on_top: true
                icon: '<i class="fa fa-users"></i>'
                items:
                    - admin.user
            app.admin.group.contenu:
                label: Content
                icon: '<i class="fa fa-briefcase"></i>'
                items:
                    - admin.node.post
            app.admin.group.parameters:
                label: Parameters
                icon: '<i class="fa fa-cogs"></i>'
                items:
                    - { label: Default Parameters, route: admin_app_parameter_default, roles: [ ROLE_ADMIN_PARAMETER_LIST ] }
                    - { label: Blog Parameters, route: admin_app_parameter_blog, roles: [ ROLE_ADMIN_PARAMETER_LIST ] }

    security:
        handler: sonata.admin.security.handler.role
        role_admin: ROLE_ADMIN
        role_super_admin: ROLE_SUPER_ADMIN

sonata_block:
    blocks:
        admin.block.statistique:
            contexts: [admin]
        admin.block.app:
            contexts: [admin]
        admin.block.server-statistique:
            contexts: [admin]
