services:
    admin.user:
        class: App\Admin\UserAdmin
        tags:
            -
                name: sonata.admin
                model_class: App\Entity\User
                controller: ~
                manager_type: orm
                group: Users
                label: User List

    admin.node.post:
        class: App\Admin\Node\PostAdmin
        tags:
            -
                name: sonata.admin
                model_class: App\Entity\Node\Post
                controller: App\Controller\Node\PostAdminController
                manager_type: orm
                group: admin
                label: Post List

    admin.parameters:
        class: App\Admin\ParameterAdmin
        tags:
            -
                name: sonata.admin
                model_class: App\Entity\Parameter
                controller: App\Controller\Admin\ParameterAdminController
                manager_type: orm
                group: Parameters
                label: Parameter List

    admin.block.server.statistique:
    admin.block.app:
        class: App\Component\Admin\AppAdminBlock
        arguments:
            - '@twig'
            - '@App\Service\ServerInformations\ServerInformationsProviderInterface'
        tags:
            - { name: sonata.block }
        class: App\Component\Admin\ServerStatistiqueAdminBlock
        arguments:
            - '@twig'
            - '@App\Service\ServerInformations\ServerInformationsProviderInterface'
        tags:
            - { name: sonata.block }