services:
    admin.user:
        class: App\Admin\UserAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\User, controller: ~, manager_type: orm, group: Users, label: User List }
